apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend.yaml
  - frontend.yaml
  - db.yaml
images:
  - name: kavindasamarawickkrama2001/vidly-backend
    newTag: v.1
  - name: kavindasamarawickkrama2001/vidly-frontend
    newTag: v.2
